apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-blue
  labels:
    app: frontend
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: blue
  template:
    metadata:
      labels:
        app: frontend
        version: blue
    spec:
      containers:
        - name: frontend-container
          image: laurapmedeiro/pwa-tfm:frontend-3.0.0
          ports:
            - containerPort: 8100
          imagePullPolicy: Always
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-blue
  labels:
    app: backend
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: blue
  template:
    metadata:
      labels:
        app: backend
        version: blue
    spec:
      containers:
        - name: backend-container
          image: laurapmedeiro/pwa-tfm:backend-3.0.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always



