apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-blue
  labels:
    app: frontend
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: blue
  template:
    metadata:
      labels:
        app: frontend
        version: blue
    spec:
      containers:
        - name: frontend-container
          image: laurapmedeiro/pwa-tfm:frontend-1.0.0
          ports:
            - containerPort: 8100
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-blue
spec:
  selector:
    app: frontend
    version: blue
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
  type: LoadBalancer  # Use NodePort or ClusterIP if necessary
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-blue
  labels:
    app: backend
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: blue
  template:
    metadata:
      labels:
        app: backend
        version: blue
    spec:
      containers:
        - name: backend-container
          image: laurapmedeiro/pwa-tfm:backend-1.0.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-blue
spec:
  selector:
    app: backend
    version: blue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
