#Base image from alpine
FROM node:20.5-alpine

#Create working directory
WORKDIR /app

# Copy package.json and package-lock.json files to working directory
COPY ["blue-green-pwa/package.json", "blue-green-pwa/package-lock.json*", "./"]

# Install IONIC and other dependencies
RUN npm install -g @ionic/cli

# Install dependencies
RUN npm install

# Add the apllication
COPY ./blue-green-pwa /app/

# Start the application
ENTRYPOINT ["ionic", "serve", "--external", "--consolelogs"]

# Make the application available on  port
EXPOSE 8100